### ISSUE TITLE
The suggested change in step 6 is undefined

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/ci-travis#45]
## Bug Report

**Current behavior**
In Step 6, we show the learner a suggested change to replace `{% site.times %}` with `{{ site.time }}`, but it appears as `undefined` because Learning Lab is trying to parse the Liquid content. 

**Reproduction**
Take the course and apply the suggested change in step 6. 

**Expected behavior**
`{{ site.time }}` should show in the suggestion, as intended in the config:

https://github.com/githubtraining/ci-travis/blob/8c4282646a9da3d320888401c8fc5a6f4d5e945b/config.yml#L179-L182

**Possible solution**
We've had situations like this in the past and have been able to use the `{% raw %}` tag. Example:

```yaml
  steps:
  - uses: actions/checkout@v2
  - name: Use Node.js {% raw %}${{ matrix.node-version }}{% endraw %}
    uses: actions/setup-node@v1
    with:
      node-version: {% raw %}${{ matrix.node-version }}{% endraw %}
  - name: npm install, and test
    run: |
      npm install
      npm test
```
